### ISSUE TITLE
PA Review: Live Chat

### ISSUE THREAD

**Issue by Wittiest** [Wittiest/WizardChat#4]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
  - [x] Mouse cursor changes to pointer on hover for buttons
- [x] Smooth, bug free navigation
- [x] Adequate and appropriate seeds
  - [x] Seed of at least one direct message or group for live-chat testing.

**Comment by xnanodax** [comment]
Awesome work!
