### ISSUE TITLE
PA Review: Direct Chats

### ISSUE THREAD

**Issue by Wittiest** [Wittiest/WizardChat#5]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
  - [x] Mouse cursor changes to pointer on hover for buttons
- [x] Smooth, bug free navigation
- [x] Adequate and appropriate seeds
  - [x] Seed of at least one direct message
- [x] Logged in users can send and receive direct messages with live updates

**Comment by xnanodax** [comment]
Awesome work so far!

Let's work on some styling
- [ ] Text alignment on DMs
![screen shot 2018-08-15 at 9 04 26 am](https://user-images.githubusercontent.com/20424731/44158725-49cdc600-a06a-11e8-8b11-f3ff78483e23.png)

- [ ] On DMs, the other person in the conversation does not have their name displayed. This only happens on group chats.

**Comment by Wittiest** [comment]
> Consider having different shapes of the speech bubbles.

I like this. I will likely try to get user profile pictures / group images and then implement this.
