### ISSUE TITLE
PA Review:  Group Chats

### ISSUE THREAD

**Issue by Wittiest** [Wittiest/WizardChat#6]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
  - [x] Mouse cursor changes to pointer on hover for buttons
- [x] Smooth, bug free navigation
- [x] Adequate and appropriate seeds
  - [x] Seed of at least one group message
- [x] Logged in users can:
  - [x] create group messages
  - [x] rename a group conversation
  - [x] create a nickname for oneself / other group members
  - [x] see other group members
  - [x] leave a group chat

**Comment by xnanodax** [comment]
- [ ] The edit buttons are really close to the edge.
![screen shot 2018-08-15 at 9 33 58 am](https://user-images.githubusercontent.com/20424731/44160483-63bdd780-a06f-11e8-8a9a-f11f4cc49c10.png)

- [ ] I would place the name of the person sending the message above the bubble.
![screen shot 2018-08-15 at 9 42 56 am 1](https://user-images.githubusercontent.com/20424731/44160565-a5e71900-a06f-11e8-944f-8aafa152c0c6.png)

**Comment by Wittiest** [comment]
> I would suggest to add padding/margin to look more similar to messenger for the options tab for group chats.

> The edit buttons are really close to the edge.

Have the new edits (live on heroku) presented acceptable margin/padding?

**Comment by xnanodax** [comment]
When typing in a group message, the time stamp goes away. 
![screen shot 2018-08-17 at 6 18 31 am](https://user-images.githubusercontent.com/20424731/44268189-8ffb6480-a1e5-11e8-84e3-53680eab969e.png)

Also consider formatting the time stamp to be more similar to Messenger!

**Comment by Wittiest** [comment]
> When typing in a group message, the time stamp goes away.

Fixed. I accidentally wasn't broadcasting this with my message creation.

> Also consider formatting the time stamp to be more similar to Messenger!

Done!
