### ISSUE TITLE
PA Review: User Search

### ISSUE THREAD

**Issue by Wittiest** [Wittiest/WizardChat#7]
- [x] Users can search for a user based on first + last name
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
  - [x] Mouse cursor changes to pointer on hover
- [x] Smooth, bug free navigation
- [x] Adequate and appropriate seeds

**Comment by xnanodax** [comment]
- [ ] there is a autocomplete="off" option on the input to get rid of the drop down 
![screen shot 2018-08-15 at 9 54 16 am](https://user-images.githubusercontent.com/20424731/44161106-3114de80-a071-11e8-97a2-e6684472d828.png)

**Comment by Wittiest** [comment]
> there is a autocomplete="off" option on the input to get rid of the drop down

I've added this. My laptop doesn't autocomplete so I can't check the functionality, but the option is appearing on the form tag.
